In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets
%matplotlib inline

In [2]:
df= datasets.load_digits()

In [3]:
data_set= pd.DataFrame(df.data,columns=df.feature_names)

In [4]:
data_set['target']= df.target

In [5]:
X= data_set.drop(['target'],axis='columns')
y= data_set.target

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size=0.20, random_state=42)

## check which model works well 

#### logistic regression

In [7]:
lr= LogisticRegression()
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

C:\Users\ST\anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9694444444444444

#### SVC

In [8]:
svc= SVC(gamma='auto')
svc.fit(X_train,y_train)
svc.score(X_test,y_test)

0.4666666666666667

#### Random Forest

In [9]:
rf= RandomForestClassifier()
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.975

## apply K-fold 

In [10]:
from sklearn.model_selection import KFold
kf= KFold(n_splits=3)# n-split mean data set ko 3 equal parts mein takseem kr do
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [11]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(test_index,train_index)
# first 3 elements for testing and rest elements for training
# us se agly 3 elements testing or baki k 3 trainig
# us se agly 3 elements testing or baki k training

[0 1 2] [3 4 5 6 7 8]
[3 4 5] [0 1 2 6 7 8]
[6 7 8] [0 1 2 3 4 5]


In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size=0.20, random_state=42)

## create function for checking the model score 

In [13]:
def check_score_model(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    print(model)
    return model.score(X_train,y_train)
    

In [14]:
print("score of logististic model",check_score_model( LogisticRegression(),X_train,X_test,y_train,y_test))


LogisticRegression()
score of logististic model 1.0


C:\Users\ST\anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [15]:
print("score of SVC model",check_score_model(SVC(),X_train,X_test,y_train,y_test))

SVC()
score of SVC model 0.9965205288796103


In [16]:
print("score of Random forest",check_score_model(RandomForestClassifier(),X_train,X_test,y_train,y_test))

RandomForestClassifier()
score of Random forest 1.0


## it is just like k fold(used for user define data set). but StratifiedKFold is used for real data set 

In [17]:
from sklearn.model_selection import StratifiedKFold
folds= StratifiedKFold(n_splits=3)

In [18]:
scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(X,y):
    X_train, X_test, y_train, y_test = df.data[train_index], df.data[test_index], \
                                       df.target[train_index], df.target[test_index]
    scores_logistic.append(check_score_model(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
    scores_svm.append(check_score_model(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(check_score_model(RandomForestClassifier(n_estimators=10), X_train, X_test, y_train, y_test))

LogisticRegression(multi_class='ovr', solver='liblinear')
SVC(gamma='auto')
RandomForestClassifier(n_estimators=10)
LogisticRegression(multi_class='ovr', solver='liblinear')
SVC(gamma='auto')
RandomForestClassifier(n_estimators=10)
LogisticRegression(multi_class='ovr', solver='liblinear')
SVC(gamma='auto')
RandomForestClassifier(n_estimators=10)


In [19]:
scores_logistic

[0.9974958263772955, 0.9974958263772955, 0.9991652754590985]

In [20]:
scores_svm

[1.0, 1.0, 1.0]

In [21]:
scores_rf

[1.0, 0.9991652754590985, 1.0]

In [22]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(), X,y)

C:\Users\ST\anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\ST\anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _che

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [24]:
cross_val_score(SVC(), X,y)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [26]:
cross_val_score(RandomForestClassifier(n_estimators=100), X,y)

array([0.93888889, 0.90833333, 0.96100279, 0.98050139, 0.9275766 ])

In [27]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),X, y, cv=10)
np.average(scores1)

0.8737212911235257

In [30]:
scores1 = cross_val_score(SVC(gamma='auto'),X, y, cv=10)
np.average(scores1)

0.48198324022346367

In [32]:
scores1 = cross_val_score(LogisticRegression(),X, y, cv=10)
np.average(scores1)

C:\Users\ST\anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\ST\anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _che

0.928193668528864

In [33]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),X, y, cv=10)
np.average(scores1)

0.8758814400993172

In [34]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=5),X, y, cv=10)
np.average(scores2)

0.8837150837988826

In [35]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=5),X, y, cv=10)
np.average(scores3)

0.8909186840471758