In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error
%matplotlib inline

In [2]:
df= pd.DataFrame([[np.NaN,8,9,5000],[np.NaN,8,6,4500],['five',6,7,6000],['two',10,10,6500],['seven',9,6,7000],['three',7,10,6200],['ten',np.nan,7,7200],['eleven',7,8,8000]],columns=['experience','test_score','interview_score','salary'])

In [3]:
df

experience  test_score  interview_score  salary
0        NaN         8.0                9    5000
1        NaN         8.0                6    4500
2       five         6.0                7    6000
3        two        10.0               10    6500
4      seven         9.0                6    7000
5      three         7.0               10    6200
6        ten         NaN                7    7200
7     eleven         7.0                8    8000

In [4]:
type(df.experience[0])

float

In [5]:
pip install word2number

Note: you may need to restart the kernel to use updated packages.


In [6]:
from word2number import w2n
import math
#df["test_score"] = df.test_score.astype(float)

m=math.floor(df.test_score.median())
df.test_score = df.test_score.fillna(m)
m

8

In [7]:
df
df.experience = df.experience.fillna('zero')


In [8]:
df.experience = df.experience.apply(w2n.word_to_num)

In [9]:
df

experience  test_score  interview_score  salary
0           0         8.0                9    5000
1           0         8.0                6    4500
2           5         6.0                7    6000
3           2        10.0               10    6500
4           7         9.0                6    7000
5           3         7.0               10    6200
6          10         8.0                7    7200
7          11         7.0                8    8000

In [10]:
reg=linear_model.LinearRegression()

In [11]:
reg.fit(df[['experience','test_score','interview_score']],df.salary)

LinearRegression()

In [12]:
reg.coef_

array([281.29548763, 184.5705968 , 220.52401747])

In [13]:
reg.intercept_

1773.7263464337702

In [14]:
reg.predict([[2,9,6]])

array([5320.59679767])

In [15]:
reg.predict([[12,10,10]])

array([9200.21834061])

# linear model from sklearn dataset

In [16]:
from sklearn.datasets import load_boston

In [17]:
df= load_boston()

In [18]:
data= pd.DataFrame([df])

In [19]:
data

data  \
0  [[0.00632, 18.0, 2.31, 0.0, 0.538, 6.575, 65.2...   

                                              target  \
0  [24.0, 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27....   

                                       feature_names  \
0  [CRIM, ZN, INDUS, CHAS, NOX, RM, AGE, DIS, RAD...   

                                               DESCR  \
0  .. _boston_dataset:\n\nBoston house prices dat...   

                                            filename  
0  C:\Users\ST\anaconda\lib\site-packages\sklearn...

In [20]:
data_set= pd.DataFrame(df.data) # getting the data(col) in form of tables
data_set

0     1      2    3      4      5     6       7    8      9     10  \
0    0.00632  18.0   2.31  0.0  0.538  6.575  65.2  4.0900  1.0  296.0  15.3   
1    0.02731   0.0   7.07  0.0  0.469  6.421  78.9  4.9671  2.0  242.0  17.8   
2    0.02729   0.0   7.07  0.0  0.469  7.185  61.1  4.9671  2.0  242.0  17.8   
3    0.03237   0.0   2.18  0.0  0.458  6.998  45.8  6.0622  3.0  222.0  18.7   
4    0.06905   0.0   2.18  0.0  0.458  7.147  54.2  6.0622  3.0  222.0  18.7   
..       ...   ...    ...  ...    ...    ...   ...     ...  ...    ...   ...   
501  0.06263   0.0  11.93  0.0  0.573  6.593  69.1  2.4786  1.0  273.0  21.0   
502  0.04527   0.0  11.93  0.0  0.573  6.120  76.7  2.2875  1.0  273.0  21.0   
503  0.06076   0.0  11.93  0.0  0.573  6.976  91.0  2.1675  1.0  273.0  21.0   
504  0.10959   0.0  11.93  0.0  0.573  6.794  89.3  2.3889  1.0  273.0  21.0   
505  0.04741   0.0  11.93  0.0  0.573  6.030  80.8  2.5050  1.0  273.0  21.0   

         11    12  
0    396.90  4.98  
1    396.90  9.14  
2    392.83  4.03  
3    394.63  2.94  
4    396.90  5.33  
..      ...   ...  
501  391.99  9.67  
502  396.90  9.08  
503  396.90  5.64  
504  393.45  6.48  
505  396.90  7.88  

[506 rows x 13 columns]

In [21]:
data_set.columns= df.feature_names # set col name , col_name must be same as the feature name

In [22]:
data_set

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   5.33  
..       ...     ...    ...  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 13 columns]

In [23]:
data_set['price']= df.target # add the price col in data set by adding the target values

In [24]:
data_set

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  price  
0       15.3  396.90   4.98   24.0  
1       17.8  396.90   9.14   21.6  
2       17.8  392.83   4.03   34.7  
3       18.7  394.63   2.94   33.4  
4       18.7  396.90   5.33   36.2  
..       ...     ...    ...    ...  
501     21.0  391.99   9.67   22.4  
502     21.0  396.90   9.08   20.6  
503     21.0  396.90   5.64   23.9  
504     21.0  393.45   6.48   22.0  
505     21.0  396.90   7.88   11.9  

[506 rows x 14 columns]

In [25]:
# now we want to seperate the independent and dependent values from the data_set

In [26]:
X= data_set.iloc[ :,:-1]# except -1 col->price table excluded
y= data_set.iloc[ :,-1] # just -1 col(price) is included

In [27]:
y

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ... 
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: price, Length: 506, dtype: float64

In [28]:
data_set

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  price  
0       15.3  396.90   4.98   24.0  
1       17.8  396.90   9.14   21.6  
2       17.8  392.83   4.03   34.7  
3       18.7  394.63   2.94   33.4  
4       18.7  396.90   5.33   36.2  
..       ...     ...    ...    ...  
501     21.0  391.99   9.67   22.4  
502     21.0  396.90   9.08   20.6  
503     21.0  396.90   5.64   23.9  
504     21.0  393.45   6.48   22.0  
505     21.0  396.90   7.88   11.9  

[506 rows x 14 columns]

In [29]:
reg=linear_model.LinearRegression()

In [30]:
reg.fit(X,y)

LinearRegression()

In [31]:
reg.coef_

array([-1.08011358e-01,  4.64204584e-02,  2.05586264e-02,  2.68673382e+00,
       -1.77666112e+01,  3.80986521e+00,  6.92224640e-04, -1.47556685e+00,
        3.06049479e-01, -1.23345939e-02, -9.52747232e-01,  9.31168327e-03,
       -5.24758378e-01])

In [32]:
reg.intercept_

36.459488385089855

In [33]:
reg.predict([[0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,21.0,396.90,7.88]])

array([22.34421229])

In [34]:
from sklearn.model_selection import cross_val_score
mse=cross_val_score(reg,X,y,scoring='neg_mean_squared_error',cv=5)

In [35]:
mse

array([-12.46030057, -26.04862111, -33.07413798, -80.76237112,
       -33.31360656])

In [36]:
m= np.mean(mse)

# Test Train split

In [37]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size=0.33, random_state=42)

In [40]:
reg.fit(X,y)
mse=cross_val_score(reg,X,y,scoring='neg_mean_squared_error',cv=5)
m= np.mean(mse)
print("intercept",reg.intercept_)
print("mean squred error",m)

intercept 36.459488385089855
mean squred error -37.13180746769922


In [41]:
reg.fit(X_train,y_train)
mse=cross_val_score(reg,X_train,y_train,scoring='neg_mean_squared_error',cv=5)
m= np.mean(mse)
print("intercept",reg.intercept_)
print("mean squred error",m)

intercept 33.33497575563571
mean squred error -25.187874739285057


### check predicted value and test value of y w.r.t R2

In [42]:
from sklearn.metrics import r2_score
y_pred= reg.predict(X_test)
r2score1= r2_score(y_pred,y_test)
print(r2score1)

0.6709558976744427
