In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error
%matplotlib inline

In [60]:
df= pd.DataFrame([[np.NaN,8,9,5000],[np.NaN,8,6,4500],['five',6,7,6000],['two',10,10,6500],['seven',9,6,7000],['three',7,10,6200],['ten',np.nan,7,7200],['eleven',7,8,8000]],columns=['experience','test_score','interview_score','salary'])

In [61]:
df

experience  test_score  interview_score  salary
0        NaN         8.0                9    5000
1        NaN         8.0                6    4500
2       five         6.0                7    6000
3        two        10.0               10    6500
4      seven         9.0                6    7000
5      three         7.0               10    6200
6        ten         NaN                7    7200
7     eleven         7.0                8    8000

In [62]:
type(df.experience[0])

float

In [63]:
pip install word2number

Note: you may need to restart the kernel to use updated packages.


In [64]:
from word2number import w2n
import math
#df["test_score"] = df.test_score.astype(float)

m=math.floor(df.test_score.median())
df.test_score = df.test_score.fillna(m)
m

8

In [67]:
df
df.experience = df.experience.fillna('zero')


In [68]:
df.experience = df.experience.apply(w2n.word_to_num)

In [69]:
df

experience  test_score  interview_score  salary
0           0         8.0                9    5000
1           0         8.0                6    4500
2           5         6.0                7    6000
3           2        10.0               10    6500
4           7         9.0                6    7000
5           3         7.0               10    6200
6          10         8.0                7    7200
7          11         7.0                8    8000

In [70]:
reg=linear_model.LinearRegression()

In [71]:
reg.fit(df[['experience','test_score','interview_score']],df.salary)

LinearRegression()

In [72]:
reg.coef_

array([281.29548763, 184.5705968 , 220.52401747])

In [73]:
reg.intercept_

1773.7263464337702

In [74]:
reg.predict([[2,9,6]])

array([5320.59679767])

In [75]:
reg.predict([[12,10,10]])

array([9200.21834061])