In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets
%matplotlib inline

In [12]:
df= datasets.load_digits()

In [5]:
data_set.shape

(1797, 65)

In [15]:
df.data[0].reshape(8,8)

array([[ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.],
       [ 0.,  0., 13., 15., 10., 15.,  5.,  0.],
       [ 0.,  3., 15.,  2.,  0., 11.,  8.,  0.],
       [ 0.,  4., 12.,  0.,  0.,  8.,  8.,  0.],
       [ 0.,  5.,  8.,  0.,  0.,  9.,  8.,  0.],
       [ 0.,  4., 11.,  0.,  1., 12.,  7.,  0.],
       [ 0.,  2., 14.,  5., 10., 12.,  0.,  0.],
       [ 0.,  0.,  6., 13., 10.,  0.,  0.,  0.]])

In [9]:
# gat possoble target values
np.unique(df.target)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
data_set= pd.DataFrame(df.data,columns=df.feature_names)
data_set['target']= df.target

In [14]:
X= data_set.drop(['target'],axis='columns')
y= data_set.target

### fit_transform 

In [ ]:
# purpose of fit_transform is fit and transform. 

In [17]:
from sklearn.preprocessing import StandardScaler

In [20]:
scaler= StandardScaler()

In [22]:
X_scaler=scaler.fit_transform(X)
X_scaler

array([[ 0.        , -0.33501649, -0.04308102, ..., -1.14664746,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -1.09493684, ...,  0.54856067,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -1.09493684, ...,  1.56568555,
         1.6951369 , -0.19600752],
       ...,
       [ 0.        , -0.33501649, -0.88456568, ..., -0.12952258,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -0.67419451, ...,  0.8876023 ,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649,  1.00877481, ...,  0.8876023 ,
        -0.26113572, -0.19600752]])

In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
X_scaler, y, test_size=0.20, random_state=42)

In [25]:
from sklearn.linear_model import LogisticRegression


In [26]:
logistic= LogisticRegression()

In [27]:
logistic.fit(X_train,y_train)

LogisticRegression()

In [28]:
logistic.score(X_test,y_test)

0.9722222222222222

# want to implement PCA

In [29]:
from sklearn.decomposition import PCA

In [30]:
pca_model= PCA(0.97)

In [32]:
X_pca=pca_model.fit_transform(X)

In [34]:
X_pca.shape

(1797, 34)

In [37]:
pca_model.n_components_

34

In [38]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
X_pca, y, test_size=0.20, random_state=42)

In [39]:
logistic.fit(X_train,y_train)

C:\Users\ST\anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [40]:
logistic.score(X_test,y_test)

0.9666666666666667